name = "flow"
main = "worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "1eea836cff0e928871149d3f870bc498"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "flow-db"
database_id = "f604da49-12a9-472b-bf1c-31a8b0f0a7c8"
