name = "flow"
main = "worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "flow-db"
database_id = "1b45fafe-4e2c-463a-b1c7-74035400e188"
migrations_dir = "worker/db"

[observability]
enabled = true
